name: Update commands

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Install dependencies
      run: npm install
      
    - name: Run script
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
      run: |
        npm run register
